In [1]:
import numpy as np
from typing import List

In [2]:
def can_unlock_library(keys: List[List[float]], tolerance: float = 1e-10) -> bool:
    """
    Args:
        keys: List of n vectors, each being a list of n floating-point numbers
        precision: Threshold for numerical calculations (default: 1e-10)

    Returns:
        bool: True if keys can unlock the library, False otherwise
    """
    # Convert to numpy array for better numerical operations
    vectors = np.array(keys, dtype=float)
    n_vectors, dimension = vectors.shape
    print("number of vectors =", n_vectors)
    print("number of dimensions =", dimension)
    
    # Check 1: Number of vectors should match the dimension for a basis
    if n_vectors != dimension:
        return False
    print("number of vectors = number of dimensions")
    
    # Check 2: Linear Independence using QR decomposition
    Q, R = np.linalg.qr(vectors.T)

    print("QR Decomposition done")
    print("Q: Orthogonal Matrix is", Q)
    print("R: Upper Triangular Matrix", R)
    
    diagonal = np.abs(np.diag(R))
    
    # If any diagonal element is close to zero, vectors are linearly dependent
    is_independent = np.all(diagonal > tolerance)
    print("are vectors independent?", is_independent)
    
    return is_independent

In [3]:
can_unlock_library([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

number of vectors = 3
number of dimensions = 3
number of vectors = number of dimensions
QR Decomposition done
Q: Orthogonal Matrix is [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
R: Upper Triangular Matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
are vectors independent? True


np.True_

In [4]:
can_unlock_library([
    [2, 0, 0],
    [0, 2, 0],
    [4, 4, 0]
])

number of vectors = 3
number of dimensions = 3
number of vectors = number of dimensions
QR Decomposition done
Q: Orthogonal Matrix is [[ 1.  0.  0.]
 [-0.  1.  0.]
 [-0. -0.  1.]]
R: Upper Triangular Matrix [[2. 0. 4.]
 [0. 2. 4.]
 [0. 0. 0.]]
are vectors independent? False


np.False_

In [5]:
can_unlock_library([
    [3, -4, 7],
    [-2, 5, 1],
    [6, 2, -3]
])

number of vectors = 3
number of dimensions = 3
number of vectors = number of dimensions
QR Decomposition done
Q: Orthogonal Matrix is [[-0.34874292  0.24534987 -0.90453403]
 [ 0.46499055 -0.79266882 -0.39428407]
 [-0.81373347 -0.55810356  0.16235226]]
R: Upper Triangular Matrix [[-8.60232527  2.20870514  1.27872403]
 [ 0.         -5.01214741  1.56107227]
 [ 0.          0.         -6.70282912]]
are vectors independent? True


np.True_

In [6]:
np.linalg.solve([
    [3, -4, 7],
    [-2, 5, 1],
    [6, 2, -3]
], [1,1545,112])

array([  4.48096886, 279.23529412, 157.78546713])

In [7]:
can_unlock_library([
    [1, 0, 0],
    [0, 1, 0],
])

number of vectors = 2
number of dimensions = 3


False